"""Declarative extraction schemas: what the generator agent produces and the daily run executes.

A schema is a list of rules. Each rule targets either an HTML page (CSS selectors) or a
JSON document (dotted paths). Rules are data, not code: nothing generated by the model is
ever executed, only interpreted.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field

FieldName = Literal[
    "title", "date", "end_date", "time", "end_time", "url", "location", "price",
    "summary", "status", "event_type", "free", "image",
]


class FieldSpec(BaseModel):
    """How to read one field from an item.

    HTML: `selector` is a CSS selector relative to the item (empty string = the item itself),
    `attr` an attribute name (href, datetime, content) or null for the text content. For the
    optional `image` field, `selector="img"` with `attr="src"` also reads lazy-loading
    attributes (data-src, srcset) and resolves the URL.
    JSON: `selector` is a dotted path relative to the item ("meta.sessions.date");
    prefix with "item." to read from the parent item when `expand_path` is used.
    """

    selector: str = ""
    attr: str | None = None
    regex: str | None = Field(default=None, description="Optional regex; capture group 1 (or whole match) replaces the value.")
    constant: str | None = Field(default=None, description="Literal value instead of reading the document.")
    join: str | None = Field(default=None, description="If several nodes match, join their texts with this separator; default keeps the first.")


class HtmlRule(BaseModel):
    kind: Literal["html"] = "html"
    container_selector: str | None = Field(
        default=None, description="CSS selector for the region holding upcoming events (e.g. the section after 'Prochains rendez-vous'). Null = whole page."
    )
    exclude_selectors: list[str] = Field(
        default_factory=list, description="CSS selectors removed before extraction (past-events sections, navigation, sidebars)."
    )
    item_selector: str = Field(description="CSS selector matching exactly one node per event.")
    fields: dict[FieldName, FieldSpec]
    date_format: str | None = Field(default=None, description="strptime format if the date field is machine-formatted (e.g. from a datetime attribute); null = French natural-language parsing.")
    notes: str = ""


class JsonRule(BaseModel):
    kind: Literal["json"] = "json"
    items_path: str = Field(description="Dotted path to the list of event items, e.g. 'list' or 'data.events'. Empty string if the root is the list.")
    expand_path: str | None = Field(
        default=None,
        description="Dotted path (relative to an item) to a sub-list producing one event per element, e.g. 'meta.sessions.event__unique'. Field paths then refer to the sub-element; use the 'item.' prefix for parent fields.",
    )
    fields: dict[FieldName, FieldSpec]
    date_format: str | None = Field(default=None, description="strptime format of the date field, e.g. '%Y%m%d' or '%Y-%m-%d %H:%M:%S'. Null = natural-language parsing.")
    time_format: str | None = Field(default=None, description="strptime format of the time field(s), e.g. '%H:%M'.")
    notes: str = ""


class ExtractionSchema(BaseModel):
    rules: list[HtmlRule | JsonRule] = Field(min_length=1)
    notes: str = Field(default="", description="What the page looks like and any caveat for future maintenance.")


class SchemaRecord(BaseModel):
    """Persisted per source in data/sources.json."""

    schema_: ExtractionSchema = Field(alias="schema")
    created: date
    validated_against_llm: bool
    agreement: float = Field(description="Jaccard agreement between schema output and direct LLM extraction at creation time.")
    generator_model: str
    version: int = 1

    model_config = {"populate_by_name": True}


class DiscoveredSource(BaseModel):
    """Output of the discovery agent."""

    url: str = Field(description="Exact URL of the page or JSON endpoint listing the venue's upcoming events.")
    kind: Literal["html", "json"]
    confidence: float = Field(ge=0, le=1)
    reasoning: str = Field(description="How the source was found and why it is the best one (2-4 sentences).")
    sample_titles: list[str] = Field(default_factory=list, description="Up to 5 event titles seen in the source, for sanity checking.")
    fallback_url: str | None = Field(default=None, description="Second-best source, if any.")
    instagram: str | None = Field(default=None, description="Instagram handle of the venue if seen during discovery (no '@', no URL).")
    facebook: str | None = Field(default=None, description="Facebook page slug of the venue if seen during discovery (the part after facebook.com/).")


class SourceRecord(BaseModel):
    venue_id: str
    source: DiscoveredSource
    discovered: date
    schema_record: SchemaRecord | None = None
    # Health tracking for the daily run.
    last_ok: date | None = None
    last_error: str | None = None
    last_event_count: int = 0
    content_hash: str | None = None
    consecutive_failures: int = 0
    regenerations: int = 0
    next_generation: date | None = None
    """When the source listed no upcoming events, schema generation is postponed until this date."""


class SourcesFile(BaseModel):
    sources: dict[str, SourceRecord] = Field(default_factory=dict)
    """Keyed by venue id."""
